function(PRINT_PACKAGE_INFO title include libraries)
    MESSAGE(STATUS "   -- ${title}:")
    foreach(inc ${include})
        MESSAGE(STATUS "      -- include: ${inc}")
    endforeach()
    foreach(lib ${libraries})
        MESSAGE(STATUS "      -- library: ${lib}")
    endforeach()
endfunction(PRINT_PACKAGE_INFO)

function(PRINT_CPLUS_FLAGS)
    MESSAGE(STATUS "${CMAKE_CXX_COMPILER_ID}: ${CMAKE_CXX_COMPILER}")
    if("${CMAKE_BUILD_TYPE}" STREQUAL "Debug" OR "${CMAKE_BUILD_TYPE}" STREQUAL "DEBUG")
        MESSAGE(STATUS "CXXFLAGS: ${CMAKE_CXX_FLAGS_DEBUG} ${CMAKE_CXX_FLAGS}")
    endif()
    if("${CMAKE_BUILD_TYPE}" STREQUAL "MinSizeRel" OR "${CMAKE_BUILD_TYPE}" STREQUAL "MINSIZEREL")
        MESSAGE(STATUS "CXXFLAGS: ${CMAKE_CXX_FLAGS_MINSIZEREL} ${CMAKE_CXX_FLAGS}")
    endif()
    if("${CMAKE_BUILD_TYPE}" STREQUAL "Release" OR "${CMAKE_BUILD_TYPE}" STREQUAL "RELEASE")
        MESSAGE(STATUS "CXXFLAGS: ${CMAKE_CXX_FLAGS_RELEASE} ${CMAKE_CXX_FLAGS}")
    endif()
    if("${CMAKE_BUILD_TYPE}" STREQUAL "RelWithDebInfo" OR "${CMAKE_BUILD_TYPE}" STREQUAL "RELWITHDEBINFO")
        MESSAGE(STATUS "CXXFLAGS: ${CMAKE_CXX_FLAGS_RELWITHDEBINFO} ${CMAKE_CXX_FLAGS}")
    endif()
endfunction(PRINT_CPLUS_FLAGS)

function(targetsummary title target)
    get_target_property(_inc ${target} INTERFACE_INCLUDE_DIRECTORIES)
    get_target_property(_lib ${target} IMPORTED_LOCATION)
    if (NOT _lib)
        get_target_property(_lib ${target} IMPORTED_LOCATION_RELEASE)
    endif()
    if (NOT _lib)
        get_target_property(_lib ${target} IMPORTED_LOCATION_DEBUG)
    endif()
    libsummary(${title} "${_inc}" "${_lib}")
endfunction(targetsummary)
